Tradução Set the font-weight for Multiple Heading Elements
reativa/traducao-freecodecamp pull request #125
Opened 2021-02-08 11:45 UTC by td-chris

Tradução do description, instructions e hints do desafio:
-Set the font-weight for Multiple Heading Elements

2021-02-09 10:15 UTC, td-chris commented
Tradução do Desafio:
-Set the line-height of Paragraphs.

2021-02-10 11:26 UTC, td-chris commented
Tradução do Desafio:
-Use a Bezier Curve to Move a Graphic.

2021-02-11 12:13 UTC, td-chris commented
Tradução do desafio:
-use a css linear gradient to create a striped element

2021-02-12 09:14 UTC, td-chris commented
Tradução do desafio:
-Use CSS Animation to Change the Hover State of a Button

2021-02-13 11:32 UTC, GabrielNSD commented on content/01-responsive-web-design/applied-visual-design/use-a-bezier-curve-to-move-a-graphic.md
> +No geral, mudar os pontos `p1` e `p2` leva a criação de diferentes curvas de Bézier, que controla a progressão da animação sobre o tempo. Aqui está um exempor de uma curva e Bézier usando valores par
a palavra "exemplo"saiu "exempor"

2021-02-13 11:39 UTC, GabrielNSD requested changes
Muito bom, tem apenas um typo em um dos arquivos, deixei um comentário na linha específica

2021-02-13 12:11 UTC, td-chris reviewed
Corrigido conforme comentario

2021-02-13 12:11 UTC, td-chris commented on content/01-responsive-web-design/applied-visual-design/use-a-bezier-curve-to-move-a-graphic.md
> +No geral, mudar os pontos `p1` e `p2` leva a criação de diferentes curvas de Bézier, que controla a progressão da animação sobre o tempo. Aqui está um exempor de uma curva e Bézier usando valores par
Ok, vou corrigir! Obrigado

2021-02-13 12:14 UTC, td-chris reviewed
Atualizado!

2021-02-13 12:21 UTC, merged