Translated align-elements-using-the-align-items-property.
reativa/traducao-freecodecamp pull request #64
Opened 2021-02-01 19:14 UTC by 3salles

Aqui está a tradução do arquivo css-flexbox/align-elements-using-the-align-items-property.

2021-02-02 03:01 UTC, vanribeiro requested changes

2021-02-02 03:01 UTC, vanribeiro commented on content/01-responsive-web-design/css-flexbox/align-elements-using-the-align-items-property.md
> +title:  Alinhando Elementos Usando a Propriedade align-items
I think it would be nice if you put "Alinhe" instead of "Alinhando". When I read the titles on freeCodeCamp, I have a personal impression to read first verb in imperative tense... as commands lines. It's just a suggestion... 😊

2021-02-02 03:01 UTC, vanribeiro commented on content/01-responsive-web-design/css-flexbox/align-elements-using-the-align-items-property.md
> +Tente as outras opções para a propriedade `align-items` no editor de códigoproperty para ver suas diferenças. Mas apenas o valor `center`  é o único que passará no teste deste desafio.
Please, review this sentence.

2021-02-02 15:09 UTC, 3salles commented on content/01-responsive-web-design/css-flexbox/align-elements-using-the-align-items-property.md
> +title:  Alinhando Elementos Usando a Propriedade align-items
I understand, I sent a new commit fixing these problems.

I am new on using Github project with other people, so I have one question: should I just  send a new updated commit?

2021-02-02 21:59 UTC, vanribeiro commented on content/01-responsive-web-design/css-flexbox/align-elements-using-the-align-items-property.md
> +title:  Alinhando Elementos Usando a Propriedade align-items
No problem. 😊 I've started on the last year...

In this case, you are working on the master branch. Then, you just need to push the new commit to your cloned repository and the PR is updated.

If you're interested to know more about it, [this is a really useful link](https://docs.github.com/pt/github/collaborating-with-issues-and-pull-requests/committing-changes-to-a-pull-request-branch-created-from-a-fork).

2021-02-03 00:26 UTC, 3salles commented on content/01-responsive-web-design/css-flexbox/align-elements-using-the-align-items-property.md
> +title:  Alinhando Elementos Usando a Propriedade align-items
Thank you, so much. I updated my commits. You link was so helpfull.

2021-02-03 00:51 UTC, vanribeiro approved these changes
Thanks about consider these text changes.

2021-02-03 00:51 UTC, merged