Tradução create visual balance using text align property
reativa/traducao-freecodecamp pull request #73
Opened 2021-02-03 10:46 UTC by td-chris

Tradução do description, istructions e hints do desafio create visual balance using text align property.

2021-02-03 21:37 UTC, jowpurcinelli requested changes

2021-02-03 21:37 UTC, jowpurcinelli commented on content/01-responsive-web-design/applied-visual-design/create-a-graphic-using-css.md
> +title: Crie um desenho gráfico usando CSS
Um desenho grafico não existe. Correto seria um gráfico

2021-02-03 21:37 UTC, jowpurcinelli commented on content/01-responsive-web-design/applied-visual-design/create-visual-balance-using-the-text-align-property.md
> +Seu código deve usar a propriedade text-align na tag `p` para justificá-la.
Como podemos descrever melhor que o codigo deve assignar o valor "justify" para a propriedade text-align?

2021-02-03 23:56 UTC, td-chris commented on content/01-responsive-web-design/applied-visual-design/create-visual-balance-using-the-text-align-property.md
> +Seu código deve usar a propriedade text-align na tag `p` para justificá-la.
Acho que ficaria legal assim:

2021-02-03 23:57 UTC, td-chris commented on content/01-responsive-web-design/applied-visual-design/create-visual-balance-using-the-text-align-property.md
> +Seu código deve usar a propriedade text-align na tag `p` para justificá-la.
Seu código deve usar a propriedade "text-align: justify" na tag `p` para justificá-la.

2021-02-03 23:57 UTC, td-chris commented on content/01-responsive-web-design/applied-visual-design/create-a-graphic-using-css.md
> +title: Crie um desenho gráfico usando CSS
Ok, vou consertar. 👍🏻

2021-02-08 17:14 UTC, closed without merging

2021-02-08 17:14 UTC, td-chris commented
O arquivos desse commit já foram traduzidos.