Tradução de 2 exercicíos
reativa/traducao-freecodecamp pull request #85
Opened 2021-02-04 12:02 UTC by cleber-santos

Corrigido erro gramatical do exercicío "change-an-element-relative..." - paragrafor > paragrafo

Traduzido exercicio - "change-animation-timing-with-keywords".
Traduzido exercicio - "change-the-position-of-overlapping-elements-with-the-z-index-property".

2021-02-05 02:57 UTC, Viniciusalgueiro commented
uma boa pratica de codigo é deixar o pull request um pouco mais descritivo com as alterações 👍

2021-02-05 13:09 UTC, cleber-santos commented
Obrigado pela dica @Viniciusalgueiro, vou melhorar as descrições dos pull requests.

2021-02-08 19:44 UTC, jowpurcinelli requested changes

2021-02-08 19:44 UTC, jowpurcinelli commented on content/01-responsive-web-design/applied-visual-design/change-animation-timing-with-keywords.md
> +Para os elementos com id de `ball1` e `ball2`, adicione uma propriedade `animation-timing-function` para cada um e defina `# ball1` para `linear` e `# ball2` para `eas-out`. Observe a diferença como
Alguns error que encontrei: 
(=> Significa deveria ser...)

`eas-out` => `ease-out`
`# ball1` => `#ball1` (Sem espaço)

2021-02-08 19:46 UTC, jowpurcinelli requested changes

2021-02-08 19:46 UTC, jowpurcinelli commented on content/01-responsive-web-design/applied-visual-design/change-animation-timing-with-keywords.md
> +Existem várias palavras-chave predefindas disponíveis para opções populares. Por exemplo, o valor padrão é `ease`, que começa devagar, acelera no meio, e depois desacelera de novo no fim. Outras opçõ
`easy-in` => `ease-in`

2021-02-08 19:49 UTC, jowpurcinelli requested changes

2021-02-08 19:49 UTC, jowpurcinelli commented on content/01-responsive-web-design/applied-visual-design/create-a-gradual-css-linear-gradient.md
> +Use um `linear-gradiente()` para o `background` do elemento `div` e defina-o a partir de uma direção de 35 graus para mudar a cor de `#CCFFFF` para `#FFCCCC`.
`linear-gradiente( )` => `linear-gradient( )`

2021-02-08 19:49 UTC, jowpurcinelli commented on content/01-responsive-web-design/applied-visual-design/create-a-gradual-css-linear-gradient.md
> +O elemento `div` deve ter um `gradiente linear` `background` seguindo com a direção e cores especificadas.
`linear-gradient` é um valor pre-definido, portanto não tem tradução

2021-02-11 20:20 UTC, closed without merging